package aichat

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/amarnathcjd/gogram/telegram"
	"google.golang.org/genai"

	"zeno/config"
	"zeno/db"
)

const GeneratedImagesDir = "/app/generated"

var validAspectRatios = map[string]bool{
	"1:1": true, "9:16": true, "16:9": true, "3:4": true, "4:3": true,
	"3:2": true, "2:3": true, "5:4": true, "4:5": true, "21:9": true,
}

var aiTools []*genai.Tool

func init() {
	var createImageParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"prompt": {
				"type": "string",
				"description": "Detailed prompt describing the image to generate"
			},
			"aspect_ratio": {
				"type": "string",
				"description": "Aspect ratio. Values: 1:1, 9:16, 16:9, 3:4, 4:3, 3:2, 2:3, 5:4, 4:5, 21:9. Empty for auto."
			},
			"high_quality": {
				"type": "boolean",
				"description": "Use HIGH mode (4K resolution). COSTS MORE - only use when @s4tyendra explicitly requests."
			}
		},
		"required": ["prompt"]
	}`), &createImageParams)

	var sendFileParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"file_path": {
				"type": "string",
				"description": "Path to the file to send"
			},
			"caption": {
				"type": "string",
				"description": "Optional custom caption to send with the file. If not provided, a default caption is used."
			}
		},
		"required": ["file_path"]
	}`), &sendFileParams)

	var runCodeParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"language": {
				"type": "string",
				"description": "Programming language: python, bash, or javascript",
				"enum": ["python", "bash", "javascript"]
			},
			"code": {
				"type": "string",
				"description": "The code to execute."
			}
		},
		"required": ["language", "code"]
	}`), &runCodeParams)

	var getLatestDataParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"query": {
				"type": "string",
				"description": "Search query for real-time web information. Results will be generated by LLM, you can ask it to structure them/just prompt like normal user."
			}
		},
		"required": ["query"]
	}`), &getLatestDataParams)

	var memoryManagerParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"action": {
				"type": "string",
				"enum": ["add", "edit", "delete"],
				"description": "Action to perform on memory"
			},
			"userid": {
				"type": "string",
				"description": "User ID to manage memories for"
			},
			"text": {
				"type": "string",
				"description": "The memory text content (required for add/edit)"
			},
			"index": {
				"type": "integer",
				"description": "The memory index 1..100 (required for edit/delete)"
			}
		},
		"required": ["action", "userid"]
	}`), &memoryManagerParams)

	var fileActionsParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"action": {
				"type": "string",
				"enum": ["read", "create", "edit", "upload"],
				"description": "Action to perform: read, create (overwrite/new), edit (find-replace or rewrite), upload (to Gemini Files API)"
			},
			"file_path": {
				"type": "string",
				"description": "Absolute path to the file inside workspace or generated spaces"
			},
			"content": {
				"type": "string",
				"description": "Text content to write (required for create and complete rewrite edit)"
			},
			"find": {
				"type": "string",
				"description": "Text to find in file (optional find-replace edit)"
			},
			"replace": {
				"type": "string",
				"description": "Text to replace with (optional find-replace edit)"
			}
		},
		"required": ["action", "file_path"]
	}`), &fileActionsParams)

	var readChatParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"chat_id": {
				"type": "integer",
				"description": "Telegram Chat ID to read from"
			},
			"limit": {
				"type": "integer",
				"description": "Number of messages to retrieve (max 50, default 10)"
			}
		},
		"required": ["chat_id"]
	}`), &readChatParams)

	var sendToChatParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"chat_id": {
				"type": "integer",
				"description": "Telegram Chat ID to send to"
			},
			"text": {
				"type": "string",
				"description": "The message text to send"
			}
		},
		"required": ["chat_id", "text"]
	}`), &sendToChatParams)

	aiTools = []*genai.Tool{
		{
			FunctionDeclarations: []*genai.FunctionDeclaration{
				{
					Name:        "create_image",
					Description: "Generate an image from a text prompt. Returns the file path of the generated image.",
					Parameters:  &createImageParams,
				},
				{
					Name:        "send_file",
					Description: "Send a file to the user in the chat with optional custom caption support.",
					Parameters:  &sendFileParams,
				},
				{
					Name:        "run_code",
					Description: "Execute code in a sandboxed container. Has access to /generated (images) and /workspace. Available: python, bash, javascript (bun). Output is truncated safely.",
					Parameters:  &runCodeParams,
				},
				{
					Name:        "get_latest_data",
					Description: "Search the web for real-time, up-to-date information. Use when asked about current events, news, recent happenings, live scores, weather, or anything requiring fresh data. Returns answer with cited sources.",
					Parameters:  &getLatestDataParams,
				},
				{
					Name:        "memory_manager",
					Description: "Add, edit, or delete persistent memories about user preferences, behaviors, or facts.",
					Parameters:  &memoryManagerParams,
				},
				{
					Name:        "file_actions",
					Description: "Perform absolute file storage tasks like read, create, edit, or upload into the Gemini Files API space.",
					Parameters:  &fileActionsParams,
				},
				{
					Name:        "read_chat",
					Description: "Retrieve recent chat message history from any accessible Telegram group, channel, or direct chat.",
					Parameters:  &readChatParams,
				},
				{
					Name:        "send_to_chat",
					Description: "Directly dispatch a text message to any accessible Telegram chat by ID.",
					Parameters:  &sendToChatParams,
				},
			},
		},
	}

	os.MkdirAll(GeneratedImagesDir, 0755)
}

func executeFunctionCall(fc *genai.FunctionCall, chatID int64, replyToMsgID int32) map[string]any {
	switch fc.Name {
	case "create_image":
		return executeCreateImage(fc.Args)
	case "send_file":
		return executeSendFile(fc.Args, chatID, replyToMsgID)
	case "run_code":
		return executeRunCode(fc.Args)
	case "get_latest_data":
		return executeGetLatestData(fc.Args)
	case "memory_manager":
		return executeMemoryManager(fc.Args)
	case "file_actions":
		return executeFileActions(fc.Args)
	case "read_chat":
		return executeReadChat(fc.Args)
	case "send_to_chat":
		return executeSendToChat(fc.Args)
	default:
		return map[string]any{
			"success": false,
			"error":   fmt.Sprintf("Unknown function: %s", fc.Name),
		}
	}
}

func executeCreateImage(args map[string]any) map[string]any {
	prompt, _ := args["prompt"].(string)
	aspectRatio, _ := args["aspect_ratio"].(string)
	highQuality, _ := args["high_quality"].(bool)

	if prompt == "" {
		return map[string]any{"success": false, "error": "prompt is required"}
	}

	if aspectRatio != "" && !validAspectRatios[aspectRatio] {
		aspectRatio = ""
	}

	model := config.ImageModel
	if highQuality {
		model = config.HighImageModel
	}

	log.Printf("[AiChat] Generating image with model %s (high=%v, aspect=%s): %s", model, highQuality, aspectRatio, prompt)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	if aspectRatio == "" {
		aspectRatio = "9:16"
	}

	imageSize := "1K"
	if highQuality {
		imageSize = "4K"
	}

	imgConfig := &genai.GenerateContentConfig{
		ResponseModalities: []string{"IMAGE"},
		ImageConfig: &genai.ImageConfig{
			AspectRatio: aspectRatio,
			ImageSize:   imageSize,
		},
	}

	resp, err := genaiClient.Models.GenerateContent(ctx, model, genai.Text(prompt), imgConfig)
	if err != nil {
		log.Printf("[AiChat] Image generation failed: %v", err)
		return map[string]any{"success": false, "error": err.Error()}
	}

	if len(resp.Candidates) == 0 {
		return map[string]any{"success": false, "error": "No image generated"}
	}

	for _, candidate := range resp.Candidates {
		for _, part := range candidate.Content.Parts {
			if part.InlineData != nil {
				ext := ".png"
				if strings.Contains(part.InlineData.MIMEType, "jpeg") {
					ext = ".jpg"
				} else if strings.Contains(part.InlineData.MIMEType, "webp") {
					ext = ".webp"
				}

				filename := fmt.Sprintf("img_%d%s", time.Now().UnixNano(), ext)
				filePath := filepath.Join(GeneratedImagesDir, filename)

				err := os.WriteFile(filePath, part.InlineData.Data, 0644)
				if err != nil {
					log.Printf("[AiChat] Failed to save image: %v", err)
					return map[string]any{"success": false, "error": "Failed to save image"}
				}

				log.Printf("[AiChat] Image saved to %s (%d bytes)", filePath, len(part.InlineData.Data))
				return map[string]any{
					"success":   true,
					"file_path": filePath,
					"prompt":    prompt,
					"size":      len(part.InlineData.Data),
				}
			}
		}
	}

	return map[string]any{"success": false, "error": "No image data in response"}
}

func executeSendFile(args map[string]any, chatID int64, replyToMsgID int32) map[string]any {
	filePath, _ := args["file_path"].(string)
	caption, _ := args["caption"].(string)

	if filePath == "" {
		return map[string]any{"success": false, "error": "file_path is required"}
	}

	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		return map[string]any{"success": false, "error": "File not found"}
	}

	if caption == "" {
		caption = "🎨 Generated image"
	}

	log.Printf("[AiChat] Sending file %s to chat %d with caption %q", filePath, chatID, caption)

	_, err := botClient.SendMedia(chatID, filePath, &telegram.MediaOptions{
		ReplyTo: &telegram.InputReplyToMessage{
			ReplyToMsgID: replyToMsgID,
		},
		Caption:       caption,
		ForceDocument: true,
	})

	if err != nil {
		log.Printf("[AiChat] Failed to send file: %v", err)
		return map[string]any{"success": false, "error": err.Error()}
	}

	return map[string]any{"success": true, "message": "File sent successfully"}
}

func executeRunCode(args map[string]any) map[string]any {
	language, _ := args["language"].(string)
	code, _ := args["code"].(string)

	if language == "" || code == "" {
		return map[string]any{"success": false, "error": "language and code are required"}
	}

	validLanguages := map[string]bool{"python": true, "bash": true, "javascript": true}
	if !validLanguages[language] {
		return map[string]any{"success": false, "error": "Invalid language. Use: python, bash, or javascript"}
	}

	containerName := os.Getenv("CODE_RUNNER_CONTAINER")
	if containerName == "" {
		containerName = "zeno-code-runner"
	}

	var cmdArgs []string
	switch language {
	case "python":
		cmdArgs = []string{"docker", "exec", containerName, "python3", "-c", code}
	case "bash":
		cmdArgs = []string{"docker", "exec", containerName, "bash", "-c", code}
	case "javascript":
		cmdArgs = []string{"docker", "exec", containerName, "bun", "-e", code}
	}

	log.Printf("[AiChat] Running code (%s): %s", language, truncateString(code, 100))

	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, cmdArgs[0], cmdArgs[1:]...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	output := stdout.String()
	errOutput := stderr.String()

	if ctx.Err() == context.DeadlineExceeded {
		return map[string]any{"success": false, "error": "Execution timed out (300s limit)"}
	}

	if err != nil {
		log.Printf("[AiChat] Code execution error: %v, stderr: %s", err, errOutput)
		return map[string]any{
			"success": false,
			"error":   fmt.Sprintf("Execution failed: %s", errOutput),
			"output":  truncateTerminalOutput(output),
		}
	}

	log.Printf("[AiChat] Code execution successful, output length: %d", len(output))
	return map[string]any{"success": true, "output": truncateTerminalOutput(output)}
}

func executeGetLatestData(args map[string]any) map[string]any {
	query, _ := args["query"].(string)
	if query == "" {
		return map[string]any{"success": false, "error": "query is required"}
	}

	log.Printf("[Perplexity] Searching: %s", truncateString(query, 100))

	result, err := perplexitySearch(query)
	if err != nil {
		log.Printf("[Perplexity] Search failed: %v", err)
		return map[string]any{"success": false, "error": err.Error()}
	}

	resp := map[string]any{
		"success": true,
		"answer":  result.Answer,
	}

	if len(result.Sources) > 0 {
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Query: %s\n\n", query))
		for i, s := range result.Sources {
			sb.WriteString(fmt.Sprintf("%d. %s\n%s\n\n", i+1, s.Name, s.URL))
		}
		if len(result.RelatedQueries) > 0 {
			sb.WriteString("Related:\n")
			for _, rq := range result.RelatedQueries {
				sb.WriteString(fmt.Sprintf("• %s\n", rq))
			}
		}

		url, err := UploadToTelegraph(fmt.Sprintf("Sources: %s", truncateString(query, 60)), sb.String())
		if err != nil {
			log.Printf("[Perplexity] Failed to upload sources to Telegraph: %v", err)
		} else {
			resp["sources_url"] = url
			log.Printf("[Perplexity] Sources uploaded: %s", url)
		}
	}

	return resp
}

func executeMemoryManager(args map[string]any) map[string]any {
	action, _ := args["action"].(string)
	userIDStr, _ := args["userid"].(string)
	text, _ := args["text"].(string)
	indexVal, hasIndex := args["index"]

	if action == "" || userIDStr == "" {
		return map[string]any{"success": false, "error": "action and userid are required"}
	}

	var userID int64
	_, err := fmt.Sscanf(userIDStr, "%d", &userID)
	if err != nil {
		return map[string]any{"success": false, "error": "invalid userid format"}
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	switch action {
	case "add":
		if text == "" {
			return map[string]any{"success": false, "error": "text is required to add memory"}
		}
		var nextIndex int
		err := db.Pool.QueryRow(ctx, `SELECT COALESCE(MAX(index), 0) + 1 FROM memories WHERE user_id = $1`, userID).Scan(&nextIndex)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		if nextIndex > 100 {
			return map[string]any{"success": false, "error": "memory limit reached (max 100)"}
		}

		_, err = db.Pool.Exec(ctx, `
			INSERT INTO memories (user_id, index, text, updated_at)
			VALUES ($1, $2, $3, NOW())`, userID, nextIndex, text)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{"success": true, "message": fmt.Sprintf("Memory added successfully at index %d", nextIndex), "index": nextIndex}

	case "edit":
		if text == "" {
			return map[string]any{"success": false, "error": "text is required to edit memory"}
		}
		if !hasIndex {
			return map[string]any{"success": false, "error": "index is required to edit memory"}
		}
		var index int
		switch v := indexVal.(type) {
		case float64:
			index = int(v)
		case int:
			index = v
		case int32:
			index = int(v)
		case int64:
			index = int(v)
		default:
			return map[string]any{"success": false, "error": "invalid index type"}
		}

		tag, err := db.Pool.Exec(ctx, `
			UPDATE memories SET text = $1, updated_at = NOW()
			WHERE user_id = $2 AND index = $3`, text, userID, index)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		if tag.RowsAffected() == 0 {
			return map[string]any{"success": false, "error": fmt.Sprintf("Memory index %d not found for user", index)}
		}
		return map[string]any{"success": true, "message": "Memory updated successfully"}

	case "delete":
		if !hasIndex {
			return map[string]any{"success": false, "error": "index is required to delete memory"}
		}
		var index int
		switch v := indexVal.(type) {
		case float64:
			index = int(v)
		case int:
			index = v
		case int32:
			index = int(v)
		case int64:
			index = int(v)
		default:
			return map[string]any{"success": false, "error": "invalid index type"}
		}

		tag, err := db.Pool.Exec(ctx, `DELETE FROM memories WHERE user_id = $1 AND index = $2`, userID, index)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		if tag.RowsAffected() == 0 {
			return map[string]any{"success": false, "error": fmt.Sprintf("Memory index %d not found for user", index)}
		}
		return map[string]any{"success": true, "message": "Memory deleted successfully"}

	default:
		return map[string]any{"success": false, "error": "unknown action"}
	}
}

func executeFileActions(args map[string]any) map[string]any {
	action, _ := args["action"].(string)
	filePath, _ := args["file_path"].(string)
	content, _ := args["content"].(string)
	findText, _ := args["find"].(string)
	replaceText, _ := args["replace"].(string)

	if action == "" || filePath == "" {
		return map[string]any{"success": false, "error": "action and file_path are required"}
	}

	cleanPath := filepath.Clean(filePath)
	if !strings.HasPrefix(cleanPath, "/workspace/") && !strings.HasPrefix(cleanPath, "/app/generated/") && !strings.HasPrefix(cleanPath, "/tmp/") {
		return map[string]any{"success": false, "error": "access denied: path outside allowed directories"}
	}

	switch action {
	case "read":
		data, err := os.ReadFile(cleanPath)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{
			"success": true,
			"content": truncateTerminalOutput(string(data)),
		}

	case "create":
		dir := filepath.Dir(cleanPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return map[string]any{"success": false, "error": fmt.Sprintf("failed to create directory: %v", err)}
		}
		err := os.WriteFile(cleanPath, []byte(content), 0644)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{"success": true, "message": "file created successfully"}

	case "edit":
		data, err := os.ReadFile(cleanPath)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		original := string(data)

		var updated string
		if findText != "" {
			if !strings.Contains(original, findText) {
				return map[string]any{"success": false, "error": "find text not found in file"}
			}
			updated = strings.Replace(original, findText, replaceText, -1)
		} else {
			updated = content
		}

		err = os.WriteFile(cleanPath, []byte(updated), 0644)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{"success": true, "message": "file edited successfully"}

	case "upload":
		return map[string]any{"success": false, "error": "Google Gemini Files API upload is not supported under the current Vertex AI backend. Use local/inline file context instead."}

	default:
		return map[string]any{"success": false, "error": "unknown file action"}
	}
}

func executeReadChat(args map[string]any) map[string]any {
	chatIDVal, _ := args["chat_id"]
	limitVal, _ := args["limit"]

	var chatID int64
	switch v := chatIDVal.(type) {
	case float64:
		chatID = int64(v)
	case int64:
		chatID = v
	default:
		return map[string]any{"success": false, "error": "invalid chat_id type"}
	}

	limit := 10
	if limitVal != nil {
		switch v := limitVal.(type) {
		case float64:
			limit = int(v)
		case int:
			limit = v
		}
	}
	if limit > 50 {
		limit = 50
	}

	messages, err := botClient.GetMessages(chatID, &telegram.SearchOption{Limit: int32(limit)})
	if err != nil {
		return map[string]any{"success": false, "error": err.Error()}
	}

	var msgsList []map[string]any
	for _, m := range messages {
		msgsList = append(msgsList, map[string]any{
			"message_id": m.ID,
			"sender":     getSenderFromMessage(&m),
			"sender_id":  m.SenderID(),
			"text":       m.Text(),
			"is_media":   m.Media() != nil,
		})
	}

	return map[string]any{
		"success":  true,
		"chat_id":  chatID,
		"messages": msgsList,
	}
}

func executeSendToChat(args map[string]any) map[string]any {
	chatIDVal, _ := args["chat_id"]
	text, _ := args["text"].(string)

	var chatID int64
	switch v := chatIDVal.(type) {
	case float64:
		chatID = int64(v)
	case int64:
		chatID = v
	default:
		return map[string]any{"success": false, "error": "invalid chat_id type"}
	}

	if text == "" {
		return map[string]any{"success": false, "error": "text is required"}
	}

	msg, err := botClient.SendMessage(chatID, text, &telegram.SendOptions{ParseMode: "Markdown"})
	if err != nil {
		msg, err = botClient.SendMessage(chatID, text, nil)
	}
	if err != nil {
		return map[string]any{"success": false, "error": err.Error()}
	}

	return map[string]any{
		"success":    true,
		"message_id": msg.ID,
		"chat_id":    chatID,
	}
}
