package aichat

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/amarnathcjd/gogram/telegram"
	"google.golang.org/genai"

	"zeno/config"
	"zeno/db"
	"zeno/modules/artifacts"
)

const GeneratedImagesDir = "/app/generated"

var validAspectRatios = map[string]bool{
	"1:1": true, "9:16": true, "16:9": true, "3:4": true, "4:3": true,
	"3:2": true, "2:3": true, "5:4": true, "4:5": true, "21:9": true,
}

var aiTools []*genai.Tool

func init() {
	var createImageParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"prompt": {
				"type": "string",
				"description": "Detailed prompt describing the image to generate"
			},
			"aspect_ratio": {
				"type": "string",
				"description": "Aspect ratio. Values: 1:1, 9:16, 16:9, 3:4, 4:3, 3:2, 2:3, 5:4, 4:5, 21:9. Empty for auto."
			},
			"high_quality": {
				"type": "boolean",
				"description": "Use HIGH mode (4K resolution). COSTS MORE - only use when @s4tyendra explicitly requests."
			}
		},
		"required": ["prompt"]
	}`), &createImageParams)

	var sendFileParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"file_path": {
				"type": "string",
				"description": "Path to the file to send"
			},
			"caption": {
				"type": "string",
				"description": "Optional custom caption to send with the file. If not provided, a default caption is used."
			}
		},
		"required": ["file_path"]
	}`), &sendFileParams)

	var runCodeParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"language": {
				"type": "string",
				"description": "Programming language: python or bash. Default: bash",
				"enum": ["python", "bash"],
				"default": "bash"
			},
			"code": {
				"type": "string",
				"description": "The code to execute."
			}
		},
		"required": ["language", "code"]
	}`), &runCodeParams)

	var getLatestDataParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"query": {
				"type": "string",
				"description": "Search query for real-time web information. Results will be generated by LLM, you can ask it to structure them/just prompt like normal user."
			}
		},
		"required": ["query"]
	}`), &getLatestDataParams)

	var memoryManagerParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"action": {
				"type": "string",
				"enum": ["add", "edit", "delete"],
				"description": "Action to perform on memory"
			},
			"userid": {
				"type": "string",
				"description": "User ID to manage memories for"
			},
			"text": {
				"type": "string",
				"description": "The memory text content (required for add/edit)"
			},
			"index": {
				"type": "integer",
				"description": "The memory index 1..100 (required for edit/delete)"
			}
		},
		"required": ["action", "userid"]
	}`), &memoryManagerParams)

	var fileActionsParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"action": {
				"type": "string",
				"enum": ["read", "create", "edit", "upload"],
				"description": "Action to perform: read, create (overwrite/new), edit (find-replace or rewrite), upload (to Gemini Files API)"
			},
			"file_path": {
				"type": "string",
				"description": "Absolute path to the file inside workspace or generated spaces"
			},
			"content": {
				"type": "string",
				"description": "Text content to write (required for create and complete rewrite edit)"
			},
			"find": {
				"type": "string",
				"description": "Text to find in file (optional find-replace edit)"
			},
			"replace": {
				"type": "string",
				"description": "Text to replace with (optional find-replace edit)"
			}
		},
		"required": ["action", "file_path"]
	}`), &fileActionsParams)

	var readChatParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"chat_id": {
				"type": "integer",
				"description": "Telegram Chat ID to read from"
			},
			"limit": {
				"type": "integer",
				"description": "Number of messages to retrieve (max 50, default 10)"
			}
		},
		"required": ["chat_id"]
	}`), &readChatParams)

	var sendToChatParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"chat_id": {
				"type": "integer",
				"description": "Telegram Chat ID to send to"
			},
			"text": {
				"type": "string",
				"description": "The message text to send"
			}
		},
		"required": ["chat_id", "text"]
	}`), &sendToChatParams)

	var listTasksParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {},
		"description": "List currently running and recently completed async code tasks."
	}`), &listTasksParams)

	var readTaskLogParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"task_id": {
				"type": "string",
				"description": "The task ID to read logs for."
			},
			"lines": {
				"type": "integer",
				"description": "Number of lines to tail from the end of the log. Default 50."
			}
		},
		"required": ["task_id"]
	}`), &readTaskLogParams)

	var viewFileParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"file_path": {
				"type": "string",
				"description": "Absolute path to the file to read"
			}
		},
		"required": ["file_path"]
	}`), &viewFileParams)

	var publishArtifactParams genai.Schema
	json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"file_path": {
				"type": "string",
				"description": "Absolute path to the file to publish"
			}
		},
		"required": ["file_path"]
	}`), &publishArtifactParams)

	aiTools = []*genai.Tool{
		{
			FunctionDeclarations: []*genai.FunctionDeclaration{
				{
					Name:        "create_image",
					Description: "Generate an image from a text prompt. Returns the file path of the generated image.",
					Parameters:  &createImageParams,
				},
				{
					Name:        "send_file",
					Description: "Send a file to the user in the chat with optional custom caption support.",
					Parameters:  &sendFileParams,
				},
				{
					Name:        "run_code",
					Description: "Execute code in a sandboxed container (computer). Has access to /generated (images) and /workspace. Available: python, bash. Output is truncated safely.",
					Parameters:  &runCodeParams,
				},
				{
					Name:        "get_latest_data",
					Description: "Search the web for real-time, up-to-date information. Use when asked about current events, news, recent happenings, live scores, weather, or anything requiring fresh data. Returns answer with cited sources.",
					Parameters:  &getLatestDataParams,
				},
				{
					Name:        "memory_manager",
					Description: "Add, edit, or delete persistent memories about user preferences, behaviors, or facts.",
					Parameters:  &memoryManagerParams,
				},
				{
					Name:        "file_actions",
					Description: "Perform absolute file storage tasks like read, create, edit, or upload into the Gemini Files API space.",
					Parameters:  &fileActionsParams,
				},
				{
					Name:        "read_chat",
					Description: "Retrieve recent chat message history from any accessible Telegram group, channel, or direct chat.",
					Parameters:  &readChatParams,
				},
				{
					Name:        "send_to_chat",
					Description: "Directly dispatch a text message to any accessible Telegram chat by ID.",
					Parameters:  &sendToChatParams,
				},
				{
					Name:        "list_tasks",
					Description: "List running and recently completed async code tasks.",
					Parameters:  &listTasksParams,
				},
				{
					Name:        "read_task_log",
					Description: "Read the output log of an async task by its ID.",
					Parameters:  &readTaskLogParams,
				},
				{
					Name:        "view_file",
					Description: "Read any local file and inject it into AI context. Images/audio/PDF → Gemini inline blob. Text/code files → plain text. Any path allowed.",
					Parameters:  &viewFileParams,
				},
				{
					Name:        "publish_artifact",
					Description: "Publish a local file as an HTTP artifact to share with the user.",
					Parameters:  &publishArtifactParams,
				},
			},
		},
	}

	os.MkdirAll(GeneratedImagesDir, 0755)
}

func executeFunctionCall(fc *genai.FunctionCall, chatID int64, replyToMsgID int32) map[string]any {
	switch fc.Name {
	case "create_image":
		return executeCreateImage(fc.Args)
	case "send_file":
		return executeSendFile(fc.Args, chatID, replyToMsgID)
	case "run_code":
		return executeRunCode(fc.Args, chatID, replyToMsgID)
	case "list_tasks":
		return executeListTasks()
	case "read_task_log":
		return executeReadTaskLog(fc.Args)
	case "view_file":
		return executeViewFile(fc.Args)
	case "publish_artifact":
		return executePublishArtifact(fc.Args)
	case "get_latest_data":
		return executeGetLatestData(fc.Args)
	case "memory_manager":
		return executeMemoryManager(fc.Args)
	case "file_actions":
		return executeFileActions(fc.Args)
	case "read_chat":
		return executeReadChat(fc.Args)
	case "send_to_chat":
		return executeSendToChat(fc.Args)
	default:
		return map[string]any{
			"success": false,
			"error":   fmt.Sprintf("Unknown function: %s", fc.Name),
		}
	}
}

func executeCreateImage(args map[string]any) map[string]any {
	prompt, _ := args["prompt"].(string)
	aspectRatio, _ := args["aspect_ratio"].(string)
	highQuality, _ := args["high_quality"].(bool)

	if prompt == "" {
		return map[string]any{"success": false, "error": "prompt is required"}
	}

	if aspectRatio != "" && !validAspectRatios[aspectRatio] {
		aspectRatio = ""
	}

	model := db.GetRuntimeModel("image", config.ImageModel)
	if highQuality {
		model = db.GetRuntimeModel("highimage", config.HighImageModel)
	}

	log.Printf("[AiChat] Generating image with model %s (high=%v, aspect=%s): %s", model, highQuality, aspectRatio, prompt)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	if aspectRatio == "" {
		aspectRatio = "9:16"
	}

	imageSize := "1K"
	if highQuality {
		imageSize = "4K"
	}

	imgConfig := &genai.GenerateContentConfig{
		ResponseModalities: []string{"IMAGE"},
		ImageConfig: &genai.ImageConfig{
			AspectRatio: aspectRatio,
			ImageSize:   imageSize,
		},
	}

	resp, err := genaiClient.Models.GenerateContent(ctx, model, genai.Text(prompt), imgConfig)
	if err != nil {
		log.Printf("[AiChat] Image generation failed: %v", err)
		return map[string]any{"success": false, "error": err.Error()}
	}

	if len(resp.Candidates) == 0 {
		return map[string]any{"success": false, "error": "No image generated"}
	}

	for _, candidate := range resp.Candidates {
		for _, part := range candidate.Content.Parts {
			if part.InlineData != nil {
				ext := ".png"
				if strings.Contains(part.InlineData.MIMEType, "jpeg") {
					ext = ".jpg"
				} else if strings.Contains(part.InlineData.MIMEType, "webp") {
					ext = ".webp"
				}

				filename := fmt.Sprintf("img_%d%s", time.Now().UnixNano(), ext)
				filePath := filepath.Join(GeneratedImagesDir, filename)

				err := os.WriteFile(filePath, part.InlineData.Data, 0644)
				if err != nil {
					log.Printf("[AiChat] Failed to save image: %v", err)
					return map[string]any{"success": false, "error": "Failed to save image"}
				}

				log.Printf("[AiChat] Image saved to %s (%d bytes)", filePath, len(part.InlineData.Data))
				return map[string]any{
					"success":   true,
					"file_path": filePath,
					"prompt":    prompt,
					"size":      len(part.InlineData.Data),
				}
			}
		}
	}

	return map[string]any{"success": false, "error": "No image data in response"}
}

func executeSendFile(args map[string]any, chatID int64, replyToMsgID int32) map[string]any {
	filePath, _ := args["file_path"].(string)
	caption, _ := args["caption"].(string)

	if filePath == "" {
		return map[string]any{"success": false, "error": "file_path is required"}
	}

	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		return map[string]any{"success": false, "error": "File not found"}
	}

	if caption == "" {
		caption = "🎨 Generated image"
	}

	log.Printf("[AiChat] Sending file %s to chat %d with caption %q", filePath, chatID, caption)

	_, err := botClient.SendMedia(chatID, filePath, &telegram.MediaOptions{
		ReplyTo: &telegram.InputReplyToMessage{
			ReplyToMsgID: replyToMsgID,
		},
		Caption:       caption,
		ForceDocument: true,
	})

	if err != nil {
		log.Printf("[AiChat] Failed to send file: %v", err)
		return map[string]any{"success": false, "error": err.Error()}
	}

	return map[string]any{"success": true, "message": "File sent successfully"}
}

func executeRunCode(args map[string]any, chatID int64, replyToMsgID int32) map[string]any {
	language, _ := args["language"].(string)
	code, _ := args["code"].(string)

	if language == "" || code == "" {
		return map[string]any{"success": false, "error": "language and code are required"}
	}

	validLanguages := map[string]bool{"python": true, "bash": true}
	if !validLanguages[language] {
		return map[string]any{"success": false, "error": "Invalid language. Use: python or bash"}
	}

	return RunTaskAsync(language, code, chatID, replyToMsgID)
}

func executeListTasks() map[string]any {
	rows, err := db.Pool.Query(context.Background(), `
		SELECT task_id, status, started_at, command 
		FROM tasks 
		ORDER BY started_at DESC LIMIT 10`)
	if err != nil {
		return map[string]any{"success": false, "error": err.Error()}
	}
	defer rows.Close()

	var tasks []map[string]any
	for rows.Next() {
		var id, status, command string
		var startedAt time.Time
		if err := rows.Scan(&id, &status, &startedAt, &command); err == nil {
			tasks = append(tasks, map[string]any{
				"task_id":           id,
				"status":            status,
				"started_at":        startedAt.Format(time.RFC3339),
				"command_preview":   command,
			})
		}
	}
	return map[string]any{"success": true, "tasks": tasks}
}

func executeReadTaskLog(args map[string]any) map[string]any {
	taskID, _ := args["task_id"].(string)
	if taskID == "" {
		return map[string]any{"success": false, "error": "task_id is required"}
	}

	lines := 50
	if l, ok := args["lines"].(float64); ok {
		lines = int(l)
	}

	var logPath string
	err := db.Pool.QueryRow(context.Background(), `SELECT log_path FROM tasks WHERE task_id = $1`, taskID).Scan(&logPath)
	if err != nil {
		return map[string]any{"success": false, "error": "Task not found"}
	}

	out, err := exec.Command("tail", "-n", fmt.Sprint(lines), logPath).Output()
	if err != nil {
		return map[string]any{"success": false, "error": fmt.Sprintf("Failed to read log: %v", err)}
	}

	return map[string]any{
		"success": true,
		"task_id": taskID,
		"content": string(out),
	}
}

func executeViewFile(args map[string]any) map[string]any {
	filePath, _ := args["file_path"].(string)
	if filePath == "" {
		return map[string]any{"success": false, "error": "file_path is required"}
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		return map[string]any{"success": false, "error": err.Error()}
	}

	mimeType := http.DetectContentType(data)
	if strings.HasPrefix(mimeType, "image/") || strings.HasPrefix(mimeType, "audio/") || mimeType == "application/pdf" {
		return map[string]any{
			"success": true,
			"inline_data": map[string]any{
				"mime_type": mimeType,
				"data":      base64.StdEncoding.EncodeToString(data),
			},
		}
	}

	ext := strings.ToLower(filepath.Ext(filePath))
	textExts := map[string]bool{
		".go": true, ".py": true, ".js": true, ".ts": true, ".json": true, 
		".yaml": true, ".yml": true, ".toml": true, ".sh": true, ".md": true, 
		".txt": true, ".html": true, ".css": true,
	}

	if strings.HasPrefix(mimeType, "text/") || textExts[ext] {
		return map[string]any{
			"success": true,
			"content": string(data),
		}
	}

	return map[string]any{"success": false, "error": "unsupported binary format: " + mimeType}
}

func executePublishArtifact(args map[string]any) map[string]any {
	filePath, _ := args["file_path"].(string)
	if filePath == "" {
		return map[string]any{"success": false, "error": "file_path is required"}
	}
	
	cleanPath := filepath.Clean(filePath)
	if _, err := os.Stat(cleanPath); os.IsNotExist(err) {
		return map[string]any{"success": false, "error": "file not found"}
	}
	
	artifactID := fmt.Sprintf("%d", time.Now().UnixNano())
	
	mimeType := "application/octet-stream"
	data, err := os.ReadFile(cleanPath)
	if err == nil {
		mimeType = http.DetectContentType(data)
	}
	
	_, err = db.Pool.Exec(context.Background(), `
		INSERT INTO artifacts (artifact_id, file_path, mime_type, created_at)
		VALUES ($1, $2, $3, NOW())`,
		artifactID, cleanPath, mimeType)
	
	if err != nil {
		return map[string]any{"success": false, "error": "db insert failed"}
	}
	
	url := artifacts.GetArtifactURL(artifactID)
	return map[string]any{
		"success":     true,
		"url":         url,
		"artifact_id": artifactID,
	}
}

func executeGetLatestData(args map[string]any) map[string]any {
	query, _ := args["query"].(string)
	if query == "" {
		return map[string]any{"success": false, "error": "query is required"}
	}

	log.Printf("[Perplexity] Searching: %s", truncateString(query, 100))

	result, err := perplexitySearch(query)
	if err != nil {
		log.Printf("[Perplexity] Search failed: %v", err)
		return map[string]any{"success": false, "error": err.Error()}
	}

	resp := map[string]any{
		"success": true,
		"answer":  result.Answer,
	}

	if len(result.Sources) > 0 {
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Query: %s\n\n", query))
		for i, s := range result.Sources {
			sb.WriteString(fmt.Sprintf("%d. %s\n%s\n\n", i+1, s.Name, s.URL))
		}
		if len(result.RelatedQueries) > 0 {
			sb.WriteString("Related:\n")
			for _, rq := range result.RelatedQueries {
				sb.WriteString(fmt.Sprintf("• %s\n", rq))
			}
		}

		url, err := UploadToTelegraph(fmt.Sprintf("Sources: %s", truncateString(query, 60)), sb.String())
		if err != nil {
			log.Printf("[Perplexity] Failed to upload sources to Telegraph: %v", err)
		} else {
			resp["sources_url"] = url
			log.Printf("[Perplexity] Sources uploaded: %s", url)
		}
	}

	return resp
}

func executeMemoryManager(args map[string]any) map[string]any {
	action, _ := args["action"].(string)
	userIDStr, _ := args["userid"].(string)
	text, _ := args["text"].(string)
	indexVal, hasIndex := args["index"]

	if action == "" || userIDStr == "" {
		return map[string]any{"success": false, "error": "action and userid are required"}
	}

	var userID int64
	_, err := fmt.Sscanf(userIDStr, "%d", &userID)
	if err != nil {
		return map[string]any{"success": false, "error": "invalid userid format"}
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	switch action {
	case "add":
		if text == "" {
			return map[string]any{"success": false, "error": "text is required to add memory"}
		}
		var nextIndex int
		err := db.Pool.QueryRow(ctx, `SELECT COALESCE(MAX(index), 0) + 1 FROM memories WHERE user_id = $1`, userID).Scan(&nextIndex)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		if nextIndex > 100 {
			return map[string]any{"success": false, "error": "memory limit reached (max 100)"}
		}

		_, err = db.Pool.Exec(ctx, `
			INSERT INTO memories (user_id, index, text, updated_at)
			VALUES ($1, $2, $3, NOW())`, userID, nextIndex, text)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{"success": true, "message": fmt.Sprintf("Memory added successfully at index %d", nextIndex), "index": nextIndex}

	case "edit":
		if text == "" {
			return map[string]any{"success": false, "error": "text is required to edit memory"}
		}
		if !hasIndex {
			return map[string]any{"success": false, "error": "index is required to edit memory"}
		}
		var index int
		switch v := indexVal.(type) {
		case float64:
			index = int(v)
		case int:
			index = v
		case int32:
			index = int(v)
		case int64:
			index = int(v)
		default:
			return map[string]any{"success": false, "error": "invalid index type"}
		}

		tag, err := db.Pool.Exec(ctx, `
			UPDATE memories SET text = $1, updated_at = NOW()
			WHERE user_id = $2 AND index = $3`, text, userID, index)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		if tag.RowsAffected() == 0 {
			return map[string]any{"success": false, "error": fmt.Sprintf("Memory index %d not found for user", index)}
		}
		return map[string]any{"success": true, "message": "Memory updated successfully"}

	case "delete":
		if !hasIndex {
			return map[string]any{"success": false, "error": "index is required to delete memory"}
		}
		var index int
		switch v := indexVal.(type) {
		case float64:
			index = int(v)
		case int:
			index = v
		case int32:
			index = int(v)
		case int64:
			index = int(v)
		default:
			return map[string]any{"success": false, "error": "invalid index type"}
		}

		tag, err := db.Pool.Exec(ctx, `DELETE FROM memories WHERE user_id = $1 AND index = $2`, userID, index)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		if tag.RowsAffected() == 0 {
			return map[string]any{"success": false, "error": fmt.Sprintf("Memory index %d not found for user", index)}
		}
		return map[string]any{"success": true, "message": "Memory deleted successfully"}

	default:
		return map[string]any{"success": false, "error": "unknown action"}
	}
}

func executeFileActions(args map[string]any) map[string]any {
	action, _ := args["action"].(string)
	filePath, _ := args["file_path"].(string)
	content, _ := args["content"].(string)
	findText, _ := args["find"].(string)
	replaceText, _ := args["replace"].(string)

	if action == "" || filePath == "" {
		return map[string]any{"success": false, "error": "action and file_path are required"}
	}

	cleanPath := filepath.Clean(filePath)
	if !strings.HasPrefix(cleanPath, "/workspace/") && !strings.HasPrefix(cleanPath, "/app/generated/") && !strings.HasPrefix(cleanPath, "/tmp/") {
		return map[string]any{"success": false, "error": "access denied: path outside allowed directories"}
	}

	switch action {
	case "read":
		data, err := os.ReadFile(cleanPath)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{
			"success": true,
			"content": truncateTerminalOutput(string(data)),
		}

	case "create":
		dir := filepath.Dir(cleanPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return map[string]any{"success": false, "error": fmt.Sprintf("failed to create directory: %v", err)}
		}
		err := os.WriteFile(cleanPath, []byte(content), 0644)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{"success": true, "message": "file created successfully"}

	case "edit":
		data, err := os.ReadFile(cleanPath)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		original := string(data)

		var updated string
		if findText != "" {
			if !strings.Contains(original, findText) {
				return map[string]any{"success": false, "error": "find text not found in file"}
			}
			updated = strings.Replace(original, findText, replaceText, -1)
		} else {
			updated = content
		}

		err = os.WriteFile(cleanPath, []byte(updated), 0644)
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
		return map[string]any{"success": true, "message": "file edited successfully"}

	case "upload":
		return map[string]any{"success": false, "error": "Google Gemini Files API upload is not supported under the current Vertex AI backend. Use local/inline file context instead."}

	default:
		return map[string]any{"success": false, "error": "unknown file action"}
	}
}

func executeReadChat(args map[string]any) map[string]any {
	chatIDVal, _ := args["chat_id"]
	limitVal, _ := args["limit"]

	var chatID int64
	switch v := chatIDVal.(type) {
	case float64:
		chatID = int64(v)
	case int64:
		chatID = v
	default:
		return map[string]any{"success": false, "error": "invalid chat_id type"}
	}

	limit := 10
	if limitVal != nil {
		switch v := limitVal.(type) {
		case float64:
			limit = int(v)
		case int:
			limit = v
		}
	}
	if limit > 200 {
		limit = 200
	}

	dummyMsg, err := botClient.SendMessage(chatID, ".", &telegram.SendOptions{Silent: true})
	if err != nil {
		return map[string]any{"success": false, "error": "failed to get anchor message"}
	}
	anchorID := dummyMsg.ID
	botClient.DeleteMessages(chatID, []int32{anchorID})

	var ids []int32
	for i := 1; i <= limit; i++ {
		id := anchorID - int32(i)
		if id > 0 {
			ids = append(ids, id)
		}
	}

	var messages []telegram.NewMessage
	if len(ids) > 0 {
		messages, err = botClient.GetMessages(chatID, &telegram.SearchOption{IDs: ids})
		if err != nil {
			return map[string]any{"success": false, "error": err.Error()}
		}
	}

	var msgsList []map[string]any
	for _, m := range messages {
		msgsList = append(msgsList, map[string]any{
			"message_id": m.ID,
			"sender":     getSenderFromMessage(&m),
			"sender_id":  m.SenderID(),
			"text":       m.Text(),
			"is_media":   m.Media() != nil,
		})
	}

	return map[string]any{
		"success":  true,
		"chat_id":  chatID,
		"messages": msgsList,
	}
}

func executeSendToChat(args map[string]any) map[string]any {
	chatIDVal, _ := args["chat_id"]
	text, _ := args["text"].(string)

	var chatID int64
	switch v := chatIDVal.(type) {
	case float64:
		chatID = int64(v)
	case int64:
		chatID = v
	default:
		return map[string]any{"success": false, "error": "invalid chat_id type"}
	}

	if text == "" {
		return map[string]any{"success": false, "error": "text is required"}
	}

	msg, err := botClient.SendMessage(chatID, text, &telegram.SendOptions{ParseMode: "Markdown"})
	if err != nil {
		msg, err = botClient.SendMessage(chatID, text, nil)
	}
	if err != nil {
		return map[string]any{"success": false, "error": err.Error()}
	}

	return map[string]any{
		"success":    true,
		"message_id": msg.ID,
		"chat_id":    chatID,
	}
}
